
no_index: 
  directory: 
    - example
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.62
name: Module-Install
author: Audrey Tang <autrijus@autrijus.org>
license: perl
build_requires: 
  Test::More: 0.42
  Test::Harness: 2.03
  File::Spec: 0
provides: 
  Module::Install::Fetch: 
    version: 0.62
    file: lib/Module/Install/Fetch.pm
  Module::Install::Deprecated: 
    version: 0.62
    file: lib/Module/Install/Deprecated.pm
  Module::Install::Bundle: 
    version: 0.62
    file: lib/Module/Install/Bundle.pm
  Module::Install::Admin::Bundle: 
    version: 0.62
    file: lib/Module/Install/Admin/Bundle.pm
  Module::Install::MakeMaker: 
    version: 0.62
    file: lib/Module/Install/MakeMaker.pm
  Module::Install::Inline: 
    version: 0.62
    file: lib/Module/Install/Inline.pm
  Module::Install::External: 
    version: 0.62
    file: lib/Module/Install/External.pm
  Module::Install::PAR: 
    version: 0.62
    file: lib/Module/Install/PAR.pm
  Module::Install::Include: 
    version: 0.62
    file: lib/Module/Install/Include.pm
  Module::Install::Build: 
    version: 0.62
    file: lib/Module/Install/Build.pm
  Module::Install::Admin::ScanDeps: 
    version: 0.62
    file: lib/Module/Install/Admin/ScanDeps.pm
  Module::Install::Admin::Manifest: 
    version: 0.62
    file: lib/Module/Install/Admin/Manifest.pm
  Module::Install::Admin: 
    version: 0.62
    file: lib/Module/Install/Admin.pm
  Module::Install::With: 
    version: 0.62
    file: lib/Module/Install/With.pm
  Module::Install::Base::FakeAdmin: 
    version: 0.62
    file: lib/Module/Install/Base.pm
  Module::Install::Metadata: 
    version: 0.62
    file: lib/Module/Install/Metadata.pm
  Module::Install::Makefile: 
    version: 0.62
    file: lib/Module/Install/Makefile.pm
  inc::Module::Install: 
    version: 0.62
    file: lib/inc/Module/Install.pm
  Module::Install::Admin::WriteAll: 
    version: 0.62
    file: lib/Module/Install/Admin/WriteAll.pm
  Module::Install::Base: 
    version: 0.62
    file: lib/Module/Install/Base.pm
  Module::Install::Admin::Find: 
    version: 0.62
    file: lib/Module/Install/Admin/Find.pm
  Module::Install::Makefile::Version: 
    version: 0.62
    file: lib/Module/Install/Makefile/Version.pm
  Module::Install: 
    version: 0.62
    file: lib/Module/Install.pm
  Module::Install::Win32: 
    version: 0.62
    file: lib/Module/Install/Win32.pm
  Module::Install::Admin::Makefile: 
    version: 0.62
    file: lib/Module/Install/Admin/Makefile.pm
  Module::Install::Admin::Metadata: 
    version: 0.62
    file: lib/Module/Install/Admin/Metadata.pm
  Module::Install::Makefile::Name: 
    version: 0.62
    file: lib/Module/Install/Makefile/Name.pm
  Module::AutoInstall: 
    version: 1.02
    file: lib/Module/AutoInstall.pm
  Module::Install::Can: 
    version: 0.62
    file: lib/Module/Install/Can.pm
  Module::Install::AutoInstall: 
    version: 0.62
    file: lib/Module/Install/AutoInstall.pm
  Module::Install::Run: 
    version: 0.62
    file: lib/Module/Install/Run.pm
  Module::Install::Admin::Include: 
    version: 0.62
    file: lib/Module/Install/Admin/Include.pm
  Module::Install::Scripts: 
    version: 0.62
    file: lib/Module/Install/Scripts.pm
  Module::Install::WriteAll: 
    version: 0.62
    file: lib/Module/Install/WriteAll.pm
  Module::Install::Compiler: 
    version: 0.62
    file: lib/Module/Install/Compiler.pm
  Module::Install::Share: 
    version: 0.62
    file: lib/Module/Install/Share.pm
requires: 
  perl: 5.004
  YAML: 0.35
recommends: 
  PAR::Dist: 0.03
  Module::ScanDeps: 0.28
  Module::Build: 0
  Module::CoreList: 0
abstract: Standalone, extensible Perl module installer
