abstract: 'Standalone, extensible Perl module installer'
author: 'Audrey Tang <autrijus@autrijus.org>'
build_requires:
  File::Spec: 0
  Test::Harness: 2.03
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Module-Install
no_index:
  directory:
    - example
    - inc
    - t
recommends:
  Module::Build: 0
  Module::CoreList: 0
  Module::ScanDeps: 0.28
  PAR::Dist: 0.03
requires:
  YAML: 0.35
  perl: 5.004
version: 0.61
