name: Module-Install
version: 0.23
abstract: Standalone, extensible Perl module installer
author: Autrijus Tang (autrijus@autrijus.org)
license: perl
distribution_type: module
build_requires:
  Test::More: 0
recommends:
  Module::ScanDeps: 0.17
  Module::CoreList: 0
  PAR::Dist: 0.03
  Archive::Tar: 0.23
  ExtUtils::Install: 0.3
  ExtUtils::ParseXS: 0
  YAML: 0.35
  Module::Build: 0
private:
  directory:
    - inc
generated_by: Module::Install version 0.23
