name: Module-Install
version: 0.38
abstract: Standalone, extensible Perl module installer
author: Autrijus Tang (autrijus@autrijus.org)
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.004
recommends:
  Module::ScanDeps: 0.28
  Module::CoreList: 0
  CPANPLUS: 0.04
  PAR::Dist: 0.03
  Module::Build: 0
no_index:
  directory:
    - example
    - inc
generated_by: Module::Install version 0.38
