name: Module-Install
version: 0.40
abstract: Standalone, extensible Perl module installer
license: perl
distribution_type: module
requires:
  perl: 5.004
recommends:
  Test::Harness: 2.03
  Test::More: 0
  Module::ScanDeps: 0.28
  Module::CoreList: 0
  CPANPLUS: 0.04
  PAR::Dist: 0.03
  Module::Build: 0
no_index:
  directory:
    - example
    - inc
generated_by: Module::Install version 0.40
