---
abstract: 'Standalone, extensible Perl module installer'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  File::Spec: 3.2701
  Test::Harness: 3.13
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.48
  YAML::Tiny: 1.33
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install
no_index:
  directory:
    - inc
    - share
    - t
    - test
requires:
  Archive::Tar: 1.44
  Devel::PPPort: 3.16
  ExtUtils::Install: 1.52
  ExtUtils::ParseXS: 2.19
  File::Remove: 1.42
  Module::Build: 0.2804
  Module::CoreList: 2.17
  Module::ScanDeps: 0.89
  PAR::Dist: 0.29
  YAML::Tiny: 1.36
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Module-Install
version: 0.81
