---
abstract: 'Standalone, extensible Perl module installer'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  File::Spec: 0.80
  Test::Harness: 2.03
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  Archive::Tar: 1.38
  Devel::PPPort: 0
  ExtUtils::Install: 1.50
  ExtUtils::ParseXS: 2.19
  File::Remove: 1.40
  Module::Build: 0.2808
  Module::CoreList: 2.13
  Module::ScanDeps: 0.83
  PAR::Dist: 0.29
  YAML::Tiny: 1.31
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Module-Install
version: 0.77
