---
abstract: 'Standalone, extensible Perl module installer'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Remove: 1.40
  File::Spec: 0.80
  Test::Harness: 2.03
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.74'
installdirs: site
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Module-Install
no_index:
  directory:
    - inc
    - t
requires:
  Archive::Tar: 1.38
  ExtUtils::Install: 1.50
  ExtUtils::ParseXS: 2.19
  Module::Build: 0.2808
  Module::CoreList: 2.15
  Module::ScanDeps: 0.83
  PAR::Dist: 0.29
  YAML::Tiny: 1.31
  perl: 5.004
tests: 't/*.t t/recursive/*.t'
version: 0.74
